[2022-07-22 00:14:13,547] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:14:12.355527+00:00 [queued]>
[2022-07-22 00:14:13,558] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:14:12.355527+00:00 [queued]>
[2022-07-22 00:14:13,561] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:14:13,562] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-22 00:14:13,563] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:14:13,579] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-22 00:14:12.355527+00:00
[2022-07-22 00:14:13,587] {standard_task_runner.py:52} INFO - Started process 9738 to run task
[2022-07-22 00:14:13,592] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-22T00:14:12.355527+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp5hvm_ndz', '--error-file', '/tmp/tmpirbhe7ju']
[2022-07-22 00:14:13,595] {standard_task_runner.py:80} INFO - Job 130: Subtask is_api_available
[2022-07-22 00:14:13,667] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:14:12.355527+00:00 [running]> on host e755cbaa46dc
[2022-07-22 00:14:13,736] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:14:12.355527+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T00:14:12.355527+00:00
[2022-07-22 00:14:13,739] {http.py:97} INFO - Poking: api/
[2022-07-22 00:14:13,749] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-22 00:14:13,752] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-22 00:14:15,773] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-22 00:14:15,798] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220722T001412, start_date=20220722T001413, end_date=20220722T001415
[2022-07-22 00:14:15,847] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 00:14:15,891] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
