[2022-07-21 17:42:03,575] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-21T17:42:02.150860+00:00 [queued]>
[2022-07-21 17:42:03,586] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-21T17:42:02.150860+00:00 [queued]>
[2022-07-21 17:42:03,587] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:42:03,589] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 17:42:03,592] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:42:03,605] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-21 17:42:02.150860+00:00
[2022-07-21 17:42:03,612] {standard_task_runner.py:52} INFO - Started process 8229 to run task
[2022-07-21 17:42:03,619] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-21T17:42:02.150860+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpcpoqtshj', '--error-file', '/tmp/tmph6l278p5']
[2022-07-21 17:42:03,621] {standard_task_runner.py:80} INFO - Job 111: Subtask is_api_available
[2022-07-21 17:42:03,689] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-21T17:42:02.150860+00:00 [running]> on host e755cbaa46dc
[2022-07-21 17:42:03,764] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T17:42:02.150860+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T17:42:02.150860+00:00
[2022-07-21 17:42:03,765] {http.py:97} INFO - Poking: api/
[2022-07-21 17:42:03,775] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-21 17:42:03,777] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-21 17:42:06,198] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-21 17:42:06,215] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220721T174202, start_date=20220721T174203, end_date=20220721T174206
[2022-07-21 17:42:06,258] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-21 17:42:06,295] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
