[2022-07-22 00:15:59,314] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user manual__2022-07-22T00:15:50.956572+00:00 [queued]>
[2022-07-22 00:15:59,326] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user manual__2022-07-22T00:15:50.956572+00:00 [queued]>
[2022-07-22 00:15:59,328] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:15:59,330] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-22 00:15:59,331] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:15:59,345] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): story_user> on 2022-07-22 00:15:50.956572+00:00
[2022-07-22 00:15:59,354] {standard_task_runner.py:52} INFO - Started process 9873 to run task
[2022-07-22 00:15:59,358] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'story_user', 'manual__2022-07-22T00:15:50.956572+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpagtbyjg3', '--error-file', '/tmp/tmprw9czuhd']
[2022-07-22 00:15:59,361] {standard_task_runner.py:80} INFO - Job 139: Subtask story_user
[2022-07-22 00:15:59,420] {task_command.py:369} INFO - Running <TaskInstance: user_processing.story_user manual__2022-07-22T00:15:50.956572+00:00 [running]> on host e755cbaa46dc
[2022-07-22 00:15:59,480] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=story_user
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:15:50.956572+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T00:15:50.956572+00:00
[2022-07-22 00:15:59,483] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-07-22 00:15:59,493] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-22 00:15:59,499] {python.py:173} INFO - Done. Returned value was: None
[2022-07-22 00:15:59,510] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=story_user, execution_date=20220722T001550, start_date=20220722T001559, end_date=20220722T001559
[2022-07-22 00:15:59,532] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 00:15:59,563] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
