[2022-07-22 00:11:48,301] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:11:46.879118+00:00 [queued]>
[2022-07-22 00:11:48,312] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:11:46.879118+00:00 [queued]>
[2022-07-22 00:11:48,314] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:11:48,315] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-22 00:11:48,317] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:11:48,330] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-22 00:11:46.879118+00:00
[2022-07-22 00:11:48,337] {standard_task_runner.py:52} INFO - Started process 9569 to run task
[2022-07-22 00:11:48,341] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-22T00:11:46.879118+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpniuzzl53', '--error-file', '/tmp/tmpw6yjgvyl']
[2022-07-22 00:11:48,344] {standard_task_runner.py:80} INFO - Job 123: Subtask is_api_available
[2022-07-22 00:11:48,402] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:11:46.879118+00:00 [running]> on host e755cbaa46dc
[2022-07-22 00:11:48,466] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:11:46.879118+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T00:11:46.879118+00:00
[2022-07-22 00:11:48,468] {http.py:97} INFO - Poking: api/
[2022-07-22 00:11:48,479] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-22 00:11:48,483] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-22 00:11:50,057] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-22 00:11:50,076] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220722T001146, start_date=20220722T001148, end_date=20220722T001150
[2022-07-22 00:11:50,135] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 00:11:50,196] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
