[2022-07-28 13:21:43,898] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-27T00:00:00+00:00 [queued]>
[2022-07-28 13:21:43,921] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-27T00:00:00+00:00 [queued]>
[2022-07-28 13:21:43,929] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 13:21:43,938] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 13:21:43,943] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 13:21:43,995] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-27 00:00:00+00:00
[2022-07-28 13:21:44,006] {standard_task_runner.py:52} INFO - Started process 78 to run task
[2022-07-28 13:21:44,015] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-27T00:00:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpo6briwn4', '--error-file', '/tmp/tmpj24f4uqr']
[2022-07-28 13:21:44,017] {standard_task_runner.py:80} INFO - Job 143: Subtask is_api_available
[2022-07-28 13:21:44,132] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-27T00:00:00+00:00 [running]> on host e755cbaa46dc
[2022-07-28 13:21:44,286] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-27T00:00:00+00:00
[2022-07-28 13:21:44,288] {http.py:97} INFO - Poking: api/
[2022-07-28 13:21:44,300] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-28 13:21:44,303] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-28 13:21:46,619] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-28 13:21:46,636] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220727T000000, start_date=20220728T132143, end_date=20220728T132146
[2022-07-28 13:21:46,662] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-28 13:21:46,704] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
