[2022-07-28 13:21:44,006] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2022-07-28 13:21:44,015] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2022-07-28 13:21:44,017] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 13:21:44,018] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 13:21:44,019] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 13:21:44,037] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-22 00:00:00+00:00
[2022-07-28 13:21:44,043] {standard_task_runner.py:52} INFO - Started process 79 to run task
[2022-07-28 13:21:44,049] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-22T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmps_4ge4du', '--error-file', '/tmp/tmpd089c54j']
[2022-07-28 13:21:44,052] {standard_task_runner.py:80} INFO - Job 145: Subtask is_api_available
[2022-07-28 13:21:44,159] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-22T00:00:00+00:00 [running]> on host e755cbaa46dc
[2022-07-28 13:21:44,313] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-22T00:00:00+00:00
[2022-07-28 13:21:44,315] {http.py:97} INFO - Poking: api/
[2022-07-28 13:21:44,385] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-28 13:21:44,404] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-28 13:21:46,678] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-28 13:21:46,690] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220722T000000, start_date=20220728T132144, end_date=20220728T132146
[2022-07-28 13:21:46,742] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-28 13:21:46,788] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
