[2022-07-21 06:04:21,683] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-21T06:04:20.444697+00:00 [queued]>
[2022-07-21 06:04:21,690] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-21T06:04:20.444697+00:00 [queued]>
[2022-07-21 06:04:21,691] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 06:04:21,693] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 06:04:21,694] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 06:04:21,704] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-21 06:04:20.444697+00:00
[2022-07-21 06:04:21,709] {standard_task_runner.py:52} INFO - Started process 287 to run task
[2022-07-21 06:04:21,712] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-21T06:04:20.444697+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp8oyq02zh', '--error-file', '/tmp/tmp1eptow1l']
[2022-07-21 06:04:21,714] {standard_task_runner.py:80} INFO - Job 82: Subtask is_api_available
[2022-07-21 06:04:21,765] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-21T06:04:20.444697+00:00 [running]> on host b03e8595b275
[2022-07-21 06:04:21,819] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T06:04:20.444697+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T06:04:20.444697+00:00
[2022-07-21 06:04:21,822] {http.py:97} INFO - Poking: api/
[2022-07-21 06:04:21,829] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-21 06:04:21,831] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-21 06:04:23,754] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-21 06:04:23,766] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220721T060420, start_date=20220721T060421, end_date=20220721T060423
[2022-07-21 06:04:23,798] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-21 06:04:23,838] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
