[2022-07-14 14:06:19,722] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-13T00:00:00+00:00 [queued]>
[2022-07-14 14:06:19,743] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-13T00:00:00+00:00 [queued]>
[2022-07-14 14:06:19,745] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-14 14:06:19,746] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-14 14:06:19,748] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-14 14:06:19,769] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-13 00:00:00+00:00
[2022-07-14 14:06:19,779] {standard_task_runner.py:52} INFO - Started process 8088 to run task
[2022-07-14 14:06:19,787] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-13T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp90we8k9_', '--error-file', '/tmp/tmp__dru_wo']
[2022-07-14 14:06:19,790] {standard_task_runner.py:80} INFO - Job 18: Subtask is_api_available
[2022-07-14 14:06:19,907] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-13T00:00:00+00:00 [running]> on host 9d087153d2d5
[2022-07-14 14:06:20,011] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-13T00:00:00+00:00
[2022-07-14 14:06:20,015] {http.py:97} INFO - Poking: api/
[2022-07-14 14:06:20,028] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-14 14:06:20,032] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-14 14:06:21,121] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-14 14:06:21,145] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220713T000000, start_date=20220714T140619, end_date=20220714T140621
[2022-07-14 14:06:21,232] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-14 14:06:21,347] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
