[2022-07-22 00:15:51,928] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:15:50.956572+00:00 [queued]>
[2022-07-22 00:15:51,935] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:15:50.956572+00:00 [queued]>
[2022-07-22 00:15:51,937] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:15:51,939] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-22 00:15:51,940] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:15:51,953] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-22 00:15:50.956572+00:00
[2022-07-22 00:15:51,966] {standard_task_runner.py:52} INFO - Started process 9854 to run task
[2022-07-22 00:15:51,969] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-22T00:15:50.956572+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpp9brr98y', '--error-file', '/tmp/tmpkw8pd1du']
[2022-07-22 00:15:51,971] {standard_task_runner.py:80} INFO - Job 135: Subtask is_api_available
[2022-07-22 00:15:52,038] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-22T00:15:50.956572+00:00 [running]> on host e755cbaa46dc
[2022-07-22 00:15:52,134] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:15:50.956572+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T00:15:50.956572+00:00
[2022-07-22 00:15:52,137] {http.py:97} INFO - Poking: api/
[2022-07-22 00:15:52,152] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-22 00:15:52,159] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-22 00:15:53,990] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-22 00:15:54,003] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220722T001550, start_date=20220722T001551, end_date=20220722T001554
[2022-07-22 00:15:54,051] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 00:15:54,103] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
