[2022-07-15 01:01:57,233] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-15T01:01:56.546523+00:00 [queued]>
[2022-07-15 01:01:57,241] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-15T01:01:56.546523+00:00 [queued]>
[2022-07-15 01:01:57,242] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 01:01:57,244] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-15 01:01:57,245] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 01:01:57,255] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-15 01:01:56.546523+00:00
[2022-07-15 01:01:57,262] {standard_task_runner.py:52} INFO - Started process 3555 to run task
[2022-07-15 01:01:57,269] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-15T01:01:56.546523+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpkrrkty1m', '--error-file', '/tmp/tmpa3x2c4ad']
[2022-07-15 01:01:57,273] {standard_task_runner.py:80} INFO - Job 47: Subtask is_api_available
[2022-07-15 01:01:57,345] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-15T01:01:56.546523+00:00 [running]> on host 042af4b110d2
[2022-07-15 01:01:57,413] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T01:01:56.546523+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-15T01:01:56.546523+00:00
[2022-07-15 01:01:57,415] {http.py:97} INFO - Poking: api/
[2022-07-15 01:01:57,426] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-15 01:01:57,431] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-15 01:01:58,377] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-15 01:01:58,397] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220715T010156, start_date=20220715T010157, end_date=20220715T010158
[2022-07-15 01:01:58,442] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-15 01:01:58,486] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
