[2022-07-21 17:42:03,517] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user manual__2022-07-21T17:42:02.150860+00:00 [queued]>
[2022-07-21 17:42:03,525] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user manual__2022-07-21T17:42:02.150860+00:00 [queued]>
[2022-07-21 17:42:03,526] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:42:03,527] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 17:42:03,529] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:42:03,540] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): story_user> on 2022-07-21 17:42:02.150860+00:00
[2022-07-21 17:42:03,546] {standard_task_runner.py:52} INFO - Started process 8227 to run task
[2022-07-21 17:42:03,550] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'story_user', 'manual__2022-07-21T17:42:02.150860+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpo4cre_4c', '--error-file', '/tmp/tmp305rbml5']
[2022-07-21 17:42:03,555] {standard_task_runner.py:80} INFO - Job 112: Subtask story_user
[2022-07-21 17:42:03,619] {task_command.py:369} INFO - Running <TaskInstance: user_processing.story_user manual__2022-07-21T17:42:02.150860+00:00 [running]> on host e755cbaa46dc
[2022-07-21 17:42:03,707] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=story_user
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T17:42:02.150860+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T17:42:02.150860+00:00
[2022-07-21 17:42:03,712] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-07-21 17:42:03,731] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-21 17:42:03,737] {python.py:173} INFO - Done. Returned value was: None
[2022-07-21 17:42:03,749] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=story_user, execution_date=20220721T174202, start_date=20220721T174203, end_date=20220721T174203
[2022-07-21 17:42:03,806] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-21 17:42:03,847] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
