[2022-07-20 04:56:27,490] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-20T04:56:26.423586+00:00 [queued]>
[2022-07-20 04:56:27,496] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-20T04:56:26.423586+00:00 [queued]>
[2022-07-20 04:56:27,497] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:56:27,498] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-20 04:56:27,499] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:56:27,508] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-20 04:56:26.423586+00:00
[2022-07-20 04:56:27,513] {standard_task_runner.py:52} INFO - Started process 338 to run task
[2022-07-20 04:56:27,516] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-20T04:56:26.423586+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9mfx_t39', '--error-file', '/tmp/tmpfzfroolp']
[2022-07-20 04:56:27,518] {standard_task_runner.py:80} INFO - Job 64: Subtask is_api_available
[2022-07-20 04:56:27,568] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-20T04:56:26.423586+00:00 [running]> on host 4800f8aada3e
[2022-07-20 04:56:27,623] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-20T04:56:26.423586+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-20T04:56:26.423586+00:00
[2022-07-20 04:56:27,625] {http.py:97} INFO - Poking: api/
[2022-07-20 04:56:27,635] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-20 04:56:27,638] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-20 04:56:28,059] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-20 04:56:28,079] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220720T045626, start_date=20220720T045627, end_date=20220720T045628
[2022-07-20 04:56:28,137] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-20 04:56:28,173] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
